### ISSUE TITLE
手机端看统计页面，显示不完全

### ISSUE THREAD

**Issue by Lewis798** [LiuYuYang01/ThriveX-Blog#10]
![81be0ee5da8d73725c9b7ac823bc1bf](https://github.com/user-attachments/assets/206cb9ad-6fe7-4647-8276-488a9d19b5f4)
如上面图片显示，这个页面在手机端显示不完全，没有自适应，如果能自适应那就很完美了

**Comment by LiuYuYang01** [comment]
感谢反馈，不过最近比较忙，过段时间适配一下移动端即可

**Comment by LiuYuYang01** [comment]
已完成数据统计页面适配：[https://github.com/LiuYuYang01/ThriveX-Blog/releases/tag/2.2](https://github.com/LiuYuYang01/ThriveX-Blog/releases/tag/2.2)
