### ISSUE TITLE
虽然不懂开发，但还是问一问：为啥不能做成php，放网站目录或者连个数据库就可以跑那种

### ISSUE THREAD

**Issue by hqylwrx** [LiuYuYang01/ThriveX-Blog#13]
虽然不懂开发，但还是问一问：为啥不能做成php，放网站目录或者连个数据库就可以跑那种

**Comment by LiuYuYang01** [comment]
其实主要原因是php在国内的占有率已经越来越少了，已经没有人再去学习这门编程语言了。即使花费大量精力学会之后几乎也找不到工作。
目前国内最流行的后端开发就是Java，假如国内有10家公司可能8个后端都是Java。
现在的php开发者多数都是以前的前辈们，我估计00后没几个php开发者了。
有一说一虽然php部署确实很方便，但我们不可能为了写个项目专门再去学习php，肯定是优先会的技术栈

**Comment by hqylwrx** [comment]
> 其实主要原因是php在国内的占有率已经越来越少了，已经没有人再去学习这门编程语言了。即使花费大量精力学会之后几乎也找不到工作。 目前国内最流行的后端开发就是Java，假如国内有10家公司可能8个后端都是Java。 现在的php开发者多数都是以前的前辈们，我估计00后没几个php开发者了。 有一说一虽然php部署确实很方便，但我们不可能为了写个项目专门再去学习php，肯定是优先会的技术栈

也是，不过搭这套系统，就要买VPS来玩了。现在也很便宜，主要是人上一定年纪，时间精力有限，不想去折腾。
有空买一台VPS折腾一番。
年轻人还是多折腾才能有收获。

**Comment by LiuYuYang01** [comment]
是的
