### ISSUE TITLE
点下一篇文章，并未跳转到文章开头

### ISSUE THREAD

**Issue by BeyondXinXin** [LiuYuYang01/ThriveX-Blog#16]
感谢开源

浏览作者博客时候遇到看完一篇文章点 上/下 一篇切换后，新文章并未从头开始

**Comment by LiuYuYang01** [comment]
感谢反馈，有时间我改一下

**Comment by LiuYuYang01** [comment]
已修复：https://github.com/LiuYuYang01/ThriveX-Blog/releases/tag/2.1.4
