### ISSUE TITLE
无法留言

### ISSUE THREAD

**Issue by wx-1124** [LiuYuYang01/ThriveX-Blog#17]
![Snipaste_2024-11-15_14-28-07](https://github.com/user-attachments/assets/a8f3f7c2-541e-4652-9f91-ddf69b9a0d61)
请问我是漏写什么了吗，一直报地址不能为空

**Comment by LiuYuYang01** [comment]
感谢反馈，我有时间解决一下，这个优先级我会放最高

**Comment by LiuYuYang01** [comment]
已经解决了，后端拉下最新代码即可
