### ISSUE TITLE
刷新页面后无法保留用户的亮暗模式的配置

### ISSUE THREAD

**Issue by qlAD** [LiuYuYang01/ThriveX-Blog#18]
#### **问题描述**

当我切换亮模式后，刷新页面就会重置为浏览器的默认模式（我的浏览器是暗色模式）。

#### **产生影响**

1. 对于习惯设置不同主题的用户刷新后都需要重新设置，比较烦人。
2. 然而，对于只在页面间导航而不刷新的用户，影响相对较小。

#### **复现步骤**

1. 在浏览器的默认设置为暗色模式的情况下，访问网站。
2. 切换页面的主题为亮模式。
3. 在不同页面间导航，主题保持为亮模式。
4. 刷新页面。
5. 页面自动切换回暗模式，而不是保留用户的亮模式选择。

#### **预期行为**

希望在我切换模式后，无论是亮还是暗，刷新页面或在页面间导航都能保留我的选择，不会被重置为浏览器的默认模式。

#### **实际行为**

用户切换主题后刷新页面，主题恢复为浏览器的默认设置（暗模式）。

#### **可能原因**

在 `Header.tsx` 中的初始化主题设置，发现每次加载页面时都会根据 prefers-color-scheme 设置来初始化模式：

```javascript
useEffect(() => {
    const { matches } = matchMedia('(prefers-color-scheme: dark)');
    setIsDark(matches);
}, []);
```

重新加载组件时，会覆盖用户手动选择的亮暗模式，导致用户选择无法在页面刷新后保存。

#### **建议方案**

1. 在切换模式的时候把用户的选择保存到 localStorage 里。
2. 在组件初始化时，优先检查 localStorage 中保存的主题设置。
3. 每次 isDark 变化时都更新 localStorage 和 HTML 类。
4. 确保在页面刷新和导航过程中都能正确读取和应用保存的主题设置。

#### **环境信息**

- 操作系统: [Fedora 41]
- 浏览器: [Microsoft Edge 130.0.0.0,  Chrome 130.0.0.0]
- 版本: [v2.1.4]

**Comment by LiuYuYang01** [comment]
感谢反馈！
大佬不愧是大佬，文档写的非常专业👍🏻

**Comment by LiuYuYang01** [comment]
// 监听系统主题变化
const mediaQuery = matchMedia('(prefers-color-scheme: dark)');
mediaQuery.addEventListener("change", (e: MediaQueryListEvent) => {
    setIsDark(e.matches)
})
        
我直接这样就好了，本地测试完毕，线上还没部署

**Comment by qlAD** [comment]
> // 监听系统主题变化 const mediaQuery = matchMedia('(prefers-color-scheme: dark)'); mediaQuery.addEventListener("change", (e: MediaQueryListEvent) => { setIsDark(e.matches) })
> 
> 我直接这样就好了，本地测试完毕，线上还没部署

谢谢你的肯定，不是大佬，只是一个互联网上的小学徒👨‍🎓。这个方法确实很巧妙，既简洁又智能。期待看到线上的效果👍
