### ISSUE TITLE
作者你好，刚开始学习nextjs,发现每次代码更改，整个页面都要白屏加载好一会。

### ISSUE THREAD

**Issue by hiddendeer** [LiuYuYang01/ThriveX-Blog#19]
这是nextjs的特性吗，写一点都要花时间等页面重新加载，请问有什么办法可以快速热更新，提高开发效率呢

**Comment by LiuYuYang01** [comment]
服务端组件导致的，客户端组件就不会出现这种情况

**Comment by LiuYuYang01** [comment]
这种情况目前我也没有解决办法，因为这是服务端组件导致的，客户端组件就不会出现这种情况

**Comment by hiddendeer** [comment]
> 这种情况目前我也没有解决办法，因为这是服务端组件导致的，客户端组件就不会出现这种情况

好的谢谢
