### ISSUE TITLE
手机端访问目录显示问题

### ISSUE THREAD

**Issue by yestool** [LiuYuYang01/ThriveX-Blog#2]
在手机端访问目录显示有如图的问题，可能要看一下如何优化。

![手机端网页测试](https://github.com/user-attachments/assets/eb62c221-d49c-4f7e-8dcd-ae1e5263525d)

**Comment by LiuYuYang01** [comment]
收到，感谢反馈

**Comment by LiuYuYang01** [comment]
已修复，拉最新代码即可
