### ISSUE TITLE
屏幕中间的两朵烟火是 Bug 还是 Feature?

### ISSUE THREAD

**Issue by ElementRef** [LiuYuYang01/ThriveX-Blog#20]
感觉像是 Bug，烟花的上下文不够高，导致在滚动的过程中，被内容遮挡一部分。

**Comment by ElementRef** [comment]
https://github.com/user-attachments/assets/6e6d7da5-7840-4867-a96c-bcf9a4dd7b77

**Comment by LiuYuYang01** [comment]
目前我这边没有出现过这种情况，理论上他的层级应该是最高的

**Comment by ElementRef** [comment]
知道了，烟花特效会导致页面卡顿，这个烟花正好卡在了中间的位置；刷新之后，烟花卡在了别的位置，就没有这个问题了。///^///

**Comment by ElementRef** [comment]
页面会导致我的 CPU 的一个核心直接拉满了

**Comment by ElementRef** [comment]
![CleanShot 2024-12-06 at 12 35 03](https://github.com/user-attachments/assets/2f7fa4df-bc5c-415c-8fd2-82c730fcb0ed)

**Comment by LiuYuYang01** [comment]
确实，这个东西有点吃配置
