### ISSUE TITLE
这个项目挺好的 不过nextjs是全栈框架 一点建议

### ISSUE THREAD

**Issue by Rakers1024** [LiuYuYang01/ThriveX-Blog#9]
个人觉得 nextjs+Spring boot挺臃肿的，java个人服务器上部署就挺消耗内存的 我个人是全栈前端，作者感兴趣 可以玩玩 nextjs+trpc+prisma的前端全栈方向，代码也在一个仓库内 这样就不用另外学java了 类型提示也完美

**Comment by LiuYuYang01** [comment]
其实我最开始也是想用纯JavaScript这套技术栈做全栈开发，但是考虑到学完了Java还没有实际做过项目，所以就打算就用Java来开发了。还有一点就是现在纯前端或纯后端很难找工作，况且很多公司后端几乎都是Java，所以我未来有可能会在后端方向花大量精力
